# Generated by Django 2.2 on 2020-09-25 19:07

from django.db import migrations, models
import salary.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=6, validators=[salary.models.validate_fields])),
                ('da', models.DecimalField(decimal_places=2, max_digits=6, validators=[salary.models.validate_fields])),
                ('hra', models.DecimalField(decimal_places=2, max_digits=6, validators=[salary.models.validate_fields])),
                ('ea', models.DecimalField(decimal_places=2, max_digits=6, validators=[salary.models.validate_fields])),
                ('pa', models.DecimalField(decimal_places=2, max_digits=6, validators=[salary.models.validate_fields])),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, validators=[salary.models.validate_fields])),
            ],
            options={
                'db_table': 'salary_structure',
            },
        ),
    ]
