# Generated by Django 2.2 on 2020-09-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Salary_structure', 'verbose_name_plural': 'Salary_structures'},
        ),
    ]
