# Generated by Django 2.2 on 2020-09-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20200925_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='id',
        ),
        migrations.AlterField(
            model_name='salary',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
