# Generated by Django 2.2 on 2020-09-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_auto_20200925_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='id',
        ),
    ]
