# Generated by Django 2.2 on 2020-09-25 20:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_remove_salary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='id',
            field=models.BigIntegerField(default=uuid.uuid1, unique=True),
        ),
    ]
