# Generated by Django 2.2 on 2020-09-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0014_salary_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='id',
        ),
    ]
