# Generated by Django 2.2 on 2020-09-25 20:35

from django.db import migrations, models
import salary.models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0015_remove_salary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='basic',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[salary.models.validate_fields]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='da',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[salary.models.validate_fields]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='ea',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[salary.models.validate_fields]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='hra',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[salary.models.validate_fields]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pa',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[salary.models.validate_fields]),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[salary.models.validate_fields]),
        ),
    ]
